"""`phomemo ui --make-app`: build Thermal.app, a Dock icon for the print screen.

The app is a stay-open AppleScript applet (osacompile ships with macOS, so
nothing is compiled here). Opening it starts `phomemo ui` from this project's
virtualenv if it isn't already running, then opens the page; clicking it in
the Dock again reopens the page; Quit stops the server. The server also stops
by itself a few minutes after the last page closes (`--idle-exit`), and the
applet quits when it notices.

Bluetooth: macOS grants Bluetooth to the *responsible app*, the app bundle a
process descends from. Started from Terminal, that's Terminal. Started from
Thermal.app it's Thermal, so the bundle declares NSBluetoothAlwaysUsageDescription
and carries its own bundle id; macOS asks once ("Thermal would like to use
Bluetooth"). Rebuilding changes the ad-hoc signature, so macOS may ask again.

The script deliberately has no `property` or `global`: a stay-open applet
writes those back into its own main.scpt when it quits, which invalidates the
code signature that the Bluetooth permission is tied to.
"""
from __future__ import annotations

import plistlib
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

APP_NAME = "Thermal"
BUNDLE_ID = "io.github.edrits.thermal"
IDLE_EXIT = 180           # s; hidden tabs poll at least once a minute
LOG = Path.home() / "Library" / "Logs" / "Thermal.log"

# Thermal design system colours (light theme).
INK, HEAT, HEAT_SOFT, SHEET, SHEET_INK = "#141414", "#c2410c", "#fbeadf", "#ffffff", "#000000"


def _q(s: str) -> str:
    """An AppleScript string literal."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def applescript(phomemo: Path, port: int = 8632, idle_exit: int = IDLE_EXIT,
                log: Path = LOG) -> str:
    url = f"http://127.0.0.1:{port}/"
    # The pkill pattern only matches servers this app started, never one
    # running in Terminal. "[u]i" matches "ui" but not the pattern itself, so
    # pkill doesn't also kill the shell running it.
    server_args = f"ui --no-open --from-app --port {port}"
    pattern = "[u]" + server_args[1:]
    start = f"quoted form of {_q(str(phomemo))} & \" {server_args} --idle-exit {idle_exit}\""
    return f'''-- Thermal.app: generated by `phomemo ui --make-app`. Rebuild rather than edit.

on run
	showPage()
end run

on reopen
	showPage()
end reopen

on idle
	if not serverUp() then quit
	return 30
end idle

on quit
	try
		do shell script "/usr/bin/pkill -TERM -f " & quoted form of {_q(pattern)}
	end try
	continue quit
end quit

on showPage()
	if not serverUp() then
		if not startServer() then
			set tailText to ""
			try
				set tailText to do shell script "/usr/bin/tail -n 4 " & quoted form of {_q(str(log))}
			end try
			display dialog "Thermal couldn't start its print server." & return & return & tailText ¬
				buttons {{"Show log", "OK"}} default button "OK" with icon caution
			if button returned of result is "Show log" then
				do shell script "/usr/bin/open -R " & quoted form of {_q(str(log))}
			end if
			quit
			return
		end if
	end if
	do shell script "/usr/bin/open " & quoted form of {_q(url)} -- the default browser
end showPage

on serverUp()
	try
		do shell script "/usr/bin/curl -sf -m 1 " & quoted form of {_q(url + "api/status")} & " | /usr/bin/grep -q instance"
		return true
	on error
		return false
	end try
end serverUp

on startServer()
	do shell script "/bin/mkdir -p " & quoted form of {_q(str(log.parent))}
	-- Every stream redirected, or do shell script waits for the server to exit.
	set pid to do shell script {start} & " >> " & quoted form of {_q(str(log))} & " 2>&1 < /dev/null & echo $!"
	repeat 60 times
		if serverUp() then return true
		try
			do shell script "/bin/kill -0 " & pid
		on error
			return false -- it exited (port taken, broken install): the log says why
		end try
		delay 0.25
	end repeat
	return false
end startServer
'''


def draw_icon(size: int = 1024):
    """The Thermal cover motif: an ink printer slab, the heat head line, and a
    sheet feeding out with a few rows of dots (thermal paper has no grey)."""
    from PIL import Image, ImageDraw

    ss = 2                                   # supersample, then downscale for smooth edges
    big = size * ss
    tile = round(big * 824 / 1024)          # macOS icon grid: 824 of 1024, centred
    radius = round(tile * 0.2237)
    u = tile / 824                           # design units below are on an 824 grid

    art = Image.new("RGBA", (tile, tile), HEAT_SOFT)
    d = ImageDraw.Draw(art)

    def box(x0, y0, x1, y1, fill, r=0):
        d.rounded_rectangle([x0 * u, y0 * u, x1 * u, y1 * u], radius=r * u, fill=fill)

    box(0, 0, 824, 300, INK)                 # the printer, bled off the top and sides
    box(112, 300, 712, 334, HEAT)            # the head line: the one accent
    box(168, 334, 656, 900, SHEET, 8)        # the sheet, feeding off the bottom
    for y, n in ((404, 9), (468, 14), (516, 12), (564, 13), (612, 7)):
        for i in range(n):
            cx, cy, r = (220 + i * 30) * u, y * u, 9 * u
            d.ellipse([cx - r, cy - r, cx + r, cy + r], fill=SHEET_INK)

    mask = Image.new("L", (tile, tile), 0)
    ImageDraw.Draw(mask).rounded_rectangle([0, 0, tile - 1, tile - 1], radius=radius, fill=255)
    canvas = Image.new("RGBA", (big, big), (0, 0, 0, 0))
    off = (big - tile) // 2
    canvas.paste(art, (off, off), mask)
    return canvas.resize((size, size), Image.Resampling.LANCZOS)


def write_icns(path: Path) -> None:
    from PIL import Image

    master = draw_icon(1024)
    with tempfile.TemporaryDirectory() as tmp:
        iconset = Path(tmp) / "icon.iconset"
        iconset.mkdir()
        for pt in (16, 32, 128, 256, 512):
            for scale in (1, 2):
                px = pt * scale
                name = f"icon_{pt}x{pt}{'@2x' if scale == 2 else ''}.png"
                master.resize((px, px), Image.Resampling.LANCZOS).save(iconset / name)
        subprocess.run(["iconutil", "-c", "icns", "-o", str(path), str(iconset)], check=True)


def phomemo_command() -> Path:
    """The `phomemo` script of the environment running this, e.g. .venv/bin/phomemo."""
    exe = Path(sys.executable).with_name("phomemo")
    if not exe.exists():
        raise FileNotFoundError(f"can't find the phomemo command next to {sys.executable}; "
                                "install the project with pip install -e . first")
    return exe


def make_app(dest_dir: Path, port: int = 8632, idle_exit: int = IDLE_EXIT) -> Path:
    if sys.platform != "darwin":
        raise ValueError("Thermal.app can only be built on macOS")
    dest_dir.mkdir(parents=True, exist_ok=True)
    dest = dest_dir / f"{APP_NAME}.app"
    with tempfile.TemporaryDirectory() as tmp:
        src = Path(tmp) / "main.applescript"
        src.write_text(applescript(phomemo_command(), port, idle_exit))
        app = Path(tmp) / f"{APP_NAME}.app"
        subprocess.run(["osacompile", "-s", "-o", str(app), str(src)], check=True,
                       capture_output=True, text=True)

        res = app / "Contents" / "Resources"
        info_path = app / "Contents" / "Info.plist"
        info = plistlib.loads(info_path.read_bytes())
        info.update({
            "CFBundleName": APP_NAME, "CFBundleDisplayName": APP_NAME,
            "CFBundleIdentifier": BUNDLE_ID, "CFBundleIconFile": "applet",
            "NSBluetoothAlwaysUsageDescription":
                "Thermal sends your pages to the Phomemo printer over Bluetooth.",
        })
        info.pop("CFBundleIconName", None)   # else the stock icon in Assets.car wins
        info_path.write_bytes(plistlib.dumps(info))
        (res / "Assets.car").unlink(missing_ok=True)
        write_icns(res / "applet.icns")
        (res / "Scripts" / "main.scpt").chmod(0o444)   # belt and braces: never self-modify

        subprocess.run(["codesign", "--force", "--deep", "--sign", "-", str(app)],
                       check=True, capture_output=True, text=True)
        if dest.exists():
            shutil.rmtree(dest)
        shutil.move(str(app), str(dest))
    dest.touch()                                    # nudge Finder to refresh the icon
    return dest
